### ISSUE TITLE
Need help connecting the ingredients property of a Pizza

### ISSUE THREAD

**Issue by Pryority** [project0204/reimagined-system#12]
We ideally want the ingredients value of each Pizza to contain an array of ingredients. I'm not sure if these should be directly in the array or as objects, or if that doesn't matter.

```
"ingredients": [
			{
				"ingredient": null
			}
		]
```

**Comment by Pryority** [comment]
I think we need to make the associations in the models/index.js file belongsToMany() associations for poth Pizza and Ingredient.

**Comment by ianaack** [comment]
models have been updated.

created a new model "PizzaIngredients" which accepts both pizza_id and ingredient_id.

now we can seed our PizzaIngredients table with pizza_ingredientsData = [{pizza_id: 1, ingredient_id: 1,},{pizza_id: 1, ingredient_id: 2}] etc
